### PR TITLE
Access to sampling methods in C# Api

### PR DESCRIPTION
**Pull request by saddam213**
Access to the `TopK` and `TopP` sampling methods in the C# API

### CODE REVIEW

**Review by baijumeswani — COMMENTED** [review]
The API changes look good to me.
Could you please address the lint error and add unit tests for both the C api as well as the C# api?

**Comment by saddam213** [comment]
Would someone be able to pickup the C tests? My C experience and environment are not the best

**Comment by baijumeswani** [comment]
@saddam213 Thanks for your contribution. :)

**Comment by saddam213** [comment]
> @saddam213 Thanks for your contribution. :)

Thanks for the help with the tests :)

**Pull request merged**
