### PR TITLE
Support Qwen in model builder

### PR DESCRIPTION
**Pull request by BowenBao**
Resolves https://github.com/microsoft/onnxruntime-genai/discussions/718

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @kunal-vaishnavi for review

**Comment by kunal-vaishnavi** [comment]
Thanks for the contribution! Can you also update the following places?

1. Add the `qwen2` model type that will show up in `genai_config.json` [here](https://github.com/microsoft/onnxruntime-genai/blob/81868e1fd4d6e671490fd90585bc9fe5f5665c49/src/models/model.cpp#L409)
2. Add Qwen to the README [here](https://github.com/microsoft/onnxruntime-genai/blob/main/README.md) to show that Qwen is now supported

**Comment by BowenBao** [comment]
Thanks @kunal-vaishnavi, updated.

I realized we will need to introduce the Qwen tokenizer as well for it to run e2e in OGA. I'm putting Qwen in "Under Development" column for now.

**Comment by yufenglee** [comment]
> Thanks @kunal-vaishnavi, updated.
> 
> I realized we will need to introduce the Qwen tokenizer as well for it to run e2e in OGA. I'm putting Qwen in "Under Development" column for now.

What tokenizer does Qwen use? Does it use same tokenizer as llama?

**Comment by yufenglee** [comment]
> > Thanks @kunal-vaishnavi, updated.
> > I realized we will need to introduce the Qwen tokenizer as well for it to run e2e in OGA. I'm putting Qwen in "Under Development" column for now.
> 
> What tokenizer does Qwen use? Does it use same tokenizer as llama?

Synced up with @wenbingl. There needs a small change to support Qwen tokenizer. He will add the change.

**Comment by wenbingl** [comment]
> > > Thanks @kunal-vaishnavi, updated.
> > > I realized we will need to introduce the Qwen tokenizer as well for it to run e2e in OGA. I'm putting Qwen in "Under Development" column for now.
> > 
> > 
> > What tokenizer does Qwen use? Does it use same tokenizer as llama?
> 
> Synced up with @wenbingl. There needs a small change to support Qwen tokenizer. He will add the change.

a quick PR is here: https://github.com/microsoft/onnxruntime-extensions/pull/781

**Comment by BowenBao** [comment]
Thank you for the quick response @wenbingl, @yufenglee! I have validated your fix enables the qwen generation e2e.

Should I wait for the PR in extension to merge, and then include the commit update in this PR?

**Comment by kunal-vaishnavi** [comment]
> Should I wait for the PR in extension to merge, and then include the commit update in this PR?

Yes, let's wait so that Qwen can be supported end-to-end with this PR.

**Comment by wenbingl** [comment]
> Thank you for the quick response @wenbingl, @yufenglee! I have validated your fix enables the qwen generation e2e.
> 
> Should I wait for the PR in extension to merge, and then include the commit update in this PR?

the PR in ort-extensions was merged.

**Comment by BowenBao** [comment]
Updated. @kunal-vaishnavi  PTAL.

**Review by kunal-vaishnavi — APPROVED** [review]

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
