### PR TITLE
Exclude libnvinfer_plugin.so.10

### PR DESCRIPTION
**Pull request by jchen351**

### CODE REVIEW

**Review by baijumeswani — APPROVED** [review]
Do we know what triggered the sudden failure?

**Comment by yufenglee** [comment]
Can we have a include list instead of an exclude list?

**Comment by jchen351** [comment]
There are so many of them from Cuda.

**Comment by jchen351** [comment]
> Do we know what triggered the sudden failure?

Might be some changes from ORT that triggers it. We are using the latest nightly build now.

**Pull request merged**
