### PR TITLE
Add ARM64 cross-compiling option on Windows

### PR DESCRIPTION
**Pull request by skyline75489**
Added `--arm64` and `--arm64ec` option to `build.py` to cross-compile ARM64 binary on x64 Windows hosts.

### CODE REVIEW

**Comment by skyline75489** [comment]
ARM64 is OK. ARM64EC is blocked by third party code defect (PR: https://github.com/mackron/dr_libs/pull/268)

**Comment by yufenglee** [comment]
> ARM64 is OK. ARM64EC is blocked by third party code defect (PR: [mackron/dr_libs#268](https://github.com/mackron/dr_libs/pull/268))

Could we enable ARM64 firstly?

**Comment by skyline75489** [comment]
@yufenglee If ARM64 is enough, merging this PR would make it work on Windows. I don't see cross-compiling option on Linux in ORT itself, thouth.

**Comment by yufenglee** [comment]
> @yufenglee If ARM64 is enough, merging this PR would make it work on Windows. I don't see cross-compiling option on Linux in ORT itself, though.

Let's go ahead with it.

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
