### PR TITLE
Catch ort exception when trying to allocate key value cache

### PR DESCRIPTION
**Pull request by baijumeswani**
Addresses https://github.com/microsoft/onnxruntime-genai/issues/980

### CODE REVIEW

**Review by RyanUnderhill — APPROVED** [review]
The diff in github looks bigger than it really is due to the indents?

Since it looks like it's just adding the try/catch unless I'm missing something.

**Comment by baijumeswani** [comment]
Yes, the indents make it look bigger than it really is.

**Comment by f2bo** [comment]
Hi. I originally reported https://github.com/microsoft/onnxruntime-genai/issues/980. While the updated error message is better, it doesn't identify the root cause unless you are familiar with the runtime's internals, especially when raised following a call to a higher level component. Perhaps, it would be more actionable if it made the association with the 'max_length' option.

**Comment by baijumeswani** [comment]
Thanks for the review. :)

**Pull request merged**
