### PR TITLE
Add performace metrics into phi3 C example.

### PR DESCRIPTION
**Pull request by daijh**

### CODE REVIEW

**Comment by daijh** [comment]
This PR adds performance measurement capabilities mirroring phi3-qa.py's --timings flag [1].

[1] onnxruntime-genai/examples/python/phi3-qa.py at main · microsoft/onnxruntime-genai
https://github.com/microsoft/onnxruntime-genai/blob/main/examples/python/phi3-qa.py

**Comment by daijh** [comment]
The output looks like below:

>Prompt length: 21, New tokens: 85, Time to first: 2.62s, Prompt tokens per second: 8.02 tps, New tokens per second: 5.09 tps

**Comment by daijh** [comment]
@microsoft-github-policy-service agree [company="intel"]

**Comment by daijh** [comment]
@microsoft-github-policy-service agree company="intel"

**Review by baijumeswani — APPROVED** [review]

**Comment by baijumeswani** [comment]
Thanks for the contribution

**Pull request merged**
